name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
      run: docker build . --file Dockerfile --tag unsuccessful/writer_api:${GITHUB_REF##*/} --build-arg NPM_TOKEN=$NPM_TOKEN
